name: CI and dev

on: 
  push:
    branches: 
      - main 

  pull_request:
    branches: 
      - main 

jobs:
  build:
    runs-on: [windows-latest]
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Nuget packages
        run: nuget restore OnlineCourse.sln

      - name: Build solution
        run: msbuild OnlineCourse
        
      - name: run test
        run: dotnet test 
        env: 
          DOTNET_VERSION: ${{ matrix.dotnet }}
        run: dotnet test -c Release --no-build
       
